#eiPlatform environment properties (eiConsole / local)

CSV_INBOUND_DIRECTORY=./data/input/inbound
CSV_ARCHIVE_DIRECTORY=./data/output/archive/csv
EDI_INBOUND_DIRECTORY=./data/input/edi
EDI_ARCHIVE_DIRECTORY=./data/output/archive/edi
EDI_834_OUTPUT_DIRECTORY=./data/output/834
CSV_OUTPUT_DIRECTORY=./data/output/csv
KICKOUT_DIRECTORY=./data/output/kickout
is_debug=true
