EDI_INBOUND_DIRECTORY=/opt/pilotfish/input/inbound
EDI_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
QCARE_OUTPUT_DIRECTORY=/opt/pilotfish/output/qcare
DEBUG_OUTPUT_DIRECTORY=/opt/pilotfish/output/debug
is_debug=true
