IF DB_ID(N'AnalyticsDemo') IS NULL
BEGIN
  CREATE DATABASE AnalyticsDemo;
END
GO

USE AnalyticsDemo;
GO

IF OBJECT_ID(N'dbo.PATIENT', N'U') IS NOT NULL DROP TABLE dbo.PATIENT;
GO

CREATE TABLE dbo.PATIENT (
  ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  LASTNAME NVARCHAR(75) NOT NULL,
  FIRSTNAME NVARCHAR(45) NULL,
  DOB NVARCHAR(32) NULL,
  ADDRESS NVARCHAR(100) NULL,
  CITY NVARCHAR(60) NULL,
  ST NVARCHAR(16) NULL,
  POSTALCODE NVARCHAR(10) NULL,
  MRN NVARCHAR(45) NULL
);
GO
