#eiPlatform environment properties (CSV to JSON demo)

CSV_INBOUND_DIRECTORY=/opt/pilotfish/input/inbound
CSV_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
JSON_OUTPUT_DIRECTORY=/opt/pilotfish/output/json
is_debug=true
