#eiPlatform environment properties (EDI 270/271 Realtime Eligibility)

REQUEST_OUTPUT_DIRECTORY=/opt/pilotfish/output/requests
EDI_270_OUTPUT_DIRECTORY=/opt/pilotfish/output/270
EDI_271_OUTPUT_DIRECTORY=/opt/pilotfish/output/271
RESPONSE_OUTPUT_DIRECTORY=/opt/pilotfish/output/responses
PAYER_X12_URL=http://mock-payer:8210/x12/270
is_debug=true
