#eiPlatform environment properties
#Tue Jul 28 09:52:45 EDT 2015
PacificLifeSpecial1122PickupDirectory=/Users/ErikWhittiker/Downloads/test
PacificLifeSpecial1122URL=http\://localhost\:8080/eiConsole/test
