is_debug=true
LAB_INBOUND_DIRECTORY=/opt/pilotfish/output/inbound
LAB_MEDITECH_OUT_DIRECTORY=/opt/pilotfish/output/meditech-outbound
LAB_KICKOUT_DIRECTORY=/opt/pilotfish/output/kickout
MEDITECH_LLP_HOST=meditech-mock
MEDITECH_LLP_PORT=2576
LAB_LLP_PORT=2575
