<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:x12:schemas:005:010:999A1:ImplementationAcknowledgment" xmlns:x12="http://schemas.x12.org/isomorph" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:x12:schemas:005:010:999A1:ImplementationAcknowledgment" elementFormDefault="qualified" version="005010">
	<xs:annotation>
		<xs:documentation xml:lang="en">Accredited Standards Committee X12 TR3 Schema: 005010X231A1 - 999 - Implementation Acknowledgment</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>2011 (c) Data Interchange Standards Association for the members of ASC X12</xs:documentation>
	</xs:annotation>
	<xs:element name="X12_005010X231A1_999A1">
		<xs:annotation>
			<xs:documentation>This X12 Transaction Set contains the format and establishes the data contents of the Implementation Acknowledgment Transaction Set (999) for use within the context of an Electronic Data Interchange (EDI) environment. The transaction set can be used to define the control structures for a set of acknowledgments to indicate the results of the syntactical and relational analysis of the electronically encoded documents, based upon a full or implemented subset of X12 transaction sets. The encoded documents are the transaction sets, which are grouped in functional groups, used in defining transactions for business data interchange. This standard does not cover the semantic meaning of the information encoded in the transaction sets.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ST_TransactionSetHeader"/>
				<xs:element ref="AK1_FunctionalGroupResponseHeader"/>
				<xs:element ref="Loop_2000" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="AK9_FunctionalGroupResponseTrailer"/>
				<xs:element ref="SE_TransactionSetTrailer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Loop_2000">
		<xs:annotation>
			<xs:documentation>Transaction Set Response Header Loop</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AK2_TransactionSetResponseHeader_2000"/>
				<xs:element ref="Loop_2100" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="IK5_TransactionSetResponseTrailer_2000"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Loop_2100">
		<xs:annotation>
			<xs:documentation>Error Identification Loop</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IK3_ErrorIdentification_2100"/>
				<xs:element ref="CTX_SegmentContext_2100" minOccurs="0" maxOccurs="9"/>
				<xs:element ref="CTX_BusinessUnitIdentifier_2100" minOccurs="0"/>
				<xs:element ref="Loop_2110" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Loop_2110">
		<xs:annotation>
			<xs:documentation>Implementation Data Element Note Loop</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IK4_ImplementationDataElementNote_2110"/>
				<xs:element ref="CTX_ElementContext_2110" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ST_TransactionSetHeader">
		<xs:annotation>
			<xs:documentation>Transaction Set Header</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ST01__TransactionSetIdentifierCode">
					<xs:annotation>
						<xs:documentation>Code uniquely identifying a Transaction Set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Identifier Code" Number="143" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="999">
								<xs:annotation>
									<xs:documentation>Implementation Acknowledgment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ST02__TransactionSetControlNumber">
					<xs:annotation>
						<xs:documentation>The unique identification number within a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Control Number" Number="329" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ST03__ImplementationConventionReference">
					<xs:annotation>
						<xs:documentation>Reference assigned to identify Implementation Convention.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Convention Reference" Number="1705" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="35"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AK1_FunctionalGroupResponseHeader">
		<xs:annotation>
			<xs:documentation>Functional Group Response Header</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AK101__FunctionalIdentifierCode">
					<xs:annotation>
						<xs:documentation>Code identifying a group of application related transaction sets.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Identifier Code" Number="479" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="2"/>
							<xs:maxLength value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK102__GroupControlNumber">
					<xs:annotation>
						<xs:documentation>Assigned number originated and maintained by the sender.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Group Control Number" Number="28" DataType="N0" MaximumLength="9"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="11"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK103__VersionReleaseOrIndustryIdentifierCode">
					<xs:annotation>
						<xs:documentation>Code indicating the version, release, subrelease, and industry identifier of the EDI standard being used.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Version / Release / Industry Identifier Code" Number="480" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AK2_TransactionSetResponseHeader_2000">
		<xs:annotation>
			<xs:documentation>Transaction Set Response Header</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AK201__TransactionSetIdentifierCode">
					<xs:annotation>
						<xs:documentation>Code uniquely identifying a Transaction Set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Identifier Code" Number="143" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK202__TransactionSetControlNumber">
					<xs:annotation>
						<xs:documentation>The unique identification number within a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Control Number" Number="329" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK203__ImplementationConventionReference" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Reference assigned to identify Implementation Convention.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Convention Reference" Number="1705" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="35"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IK3_ErrorIdentification_2100">
		<xs:annotation>
			<xs:documentation>Error Identification</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IK301__SegmentIDCode">
					<xs:annotation>
						<xs:documentation>Code defining the segment ID of the data segment in error (See Appendix A - Number 77).</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment ID Code" Number="721" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="2"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK302__SegmentPositionInTransactionSet">
					<xs:annotation>
						<xs:documentation>The numerical count position of this data segment from the start of the transaction set: the transaction set header is count position 1.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment Position in Transaction Set" Number="719" DataType="N0" MaximumLength="10"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK303__LoopIdentifierCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The loop ID number given on the transaction set diagram is the value for this data element in segments LS and LE.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Loop Identifier Code" Number="447" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK304__ImplementationSegmentSyntaxErrorCode">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a segment.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Segment Syntax Error Code" Number="620" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Unrecognized segment ID</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Unexpected segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Required Segment Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Loop Occurs Over Maximum Times</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Segment Exceeds Maximum Use</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Segment Not in Defined Transaction Set</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Segment Not in Proper Sequence</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Segment Has Data Element Errors</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I4">
								<xs:annotation>
									<xs:documentation>Implementation "Not Used" Segment Present</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Dependent Segment Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I7">
								<xs:annotation>
									<xs:documentation>Implementation Loop Occurs Under Minimum Times</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I8">
								<xs:annotation>
									<xs:documentation>Implementation Segment Below Minimum Use</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I9">
								<xs:annotation>
									<xs:documentation>Implementation Dependent "Not Used" Segment Present</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CTX_SegmentContext_2100">
		<xs:annotation>
			<xs:documentation>Segment Context</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CTX01_ContextIdentification_2100" maxOccurs="10">
					<xs:annotation>
						<xs:documentation>Holds information to identify a context</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX01_01_ContextName">
								<xs:annotation>
									<xs:documentation>Holds the name or `tag' of a context.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Name" Number="9999" DataType="AN"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX01_02" minOccurs="0">
								<xs:annotation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Reference" Number="9998" DataType="AN"/>
										<x12:TR3_Info Used="No"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CTX02__SegmentIDCode">
					<xs:annotation>
						<xs:documentation>Code defining the segment ID of the data segment in error (See Appendix A - Number 77).</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment ID Code" Number="721" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="2"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX03__SegmentPositionInTransactionSet">
					<xs:annotation>
						<xs:documentation>The numerical count position of this data segment from the start of the transaction set: the transaction set header is count position 1.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment Position in Transaction Set" Number="719" DataType="N0" MaximumLength="10"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX04__LoopIdentifierCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The loop ID number given on the transaction set diagram is the value for this data element in segments LS and LE.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Loop Identifier Code" Number="447" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX05_PositionInSegment_2100" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating the relative position of the simple data element or composite data structure in error within a segment, count beginning with 1 for the position immediately following the segment ID; additionally indicating the relative position of a repeating structure in error, count beginning with 1 for the position immediately following the preceding element separator; additionally indicating the relative position of a component of a composite data structure in error, count beginning with 1 for the position following the preceding element or repetition separator</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX05_01_ElementPositionInSegment">
								<xs:annotation>
									<xs:documentation>This is used to indicate the relative position of a simple data element or the relative position of a composite data structure with the relative position of the component within the composite data structure.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Element Position in Segment" Number="722" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX05_02_ComponentDataElementPositionInComposite" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the component data element position within the composite that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Component Data Element Position in Composite" Number="1528" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX05_03_RepeatingDataElementPosition" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the specific repetition of a data element that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Repeating Data Element Position" Number="1686" DataType="N0" MaximumLength="4"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CTX06_ReferenceInSegment_2100" minOccurs="0">
					<xs:annotation>
						<xs:documentation>To hold the reference number of a data element and optionally a component data element within a composite</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX06_01_DataElementReferenceNumber">
								<xs:annotation>
									<xs:documentation>Reference number used to locate the data element in the Data Element Dictionary.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Data Element Reference Number" Number="725" DataType="N0" MaximumLength="4"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX06_02" minOccurs="0">
								<xs:annotation>
									<xs:appinfo>
										<x12:STD_Info Name="Data Element Reference Number" Number="725" DataType="N0" MaximumLength="4"/>
										<x12:TR3_Info Used="No"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CTX_BusinessUnitIdentifier_2100">
		<xs:annotation>
			<xs:documentation>Business Unit Identifier</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CTX01_ContextIdentification_2100" maxOccurs="10">
					<xs:annotation>
						<xs:documentation>Holds information to identify a context</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX01_01_ContextName">
								<xs:annotation>
									<xs:documentation>Holds the name or `tag' of a context.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Name" Number="9999" DataType="AN"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX01_02_ContextReference">
								<xs:annotation>
									<xs:documentation>Holds a reference to or for a context.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Reference" Number="9998" DataType="AN"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CTX02" minOccurs="0">
					<xs:annotation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment ID Code" Number="721" DataType="ID"/>
							<x12:TR3_Info Used="No"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="2"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX03" minOccurs="0">
					<xs:annotation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment Position in Transaction Set" Number="719" DataType="N0" MaximumLength="10"/>
							<x12:TR3_Info Used="No"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX04" minOccurs="0">
					<xs:annotation>
						<xs:appinfo>
							<x12:STD_Info Name="Loop Identifier Code" Number="447" DataType="AN"/>
							<x12:TR3_Info Used="No"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX05" minOccurs="0">
					<xs:annotation>
						<xs:appinfo>
							<x12:TR3_Info Used="No"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX06" minOccurs="0">
					<xs:annotation>
						<xs:appinfo>
							<x12:TR3_Info Used="No"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IK4_ImplementationDataElementNote_2110">
		<xs:annotation>
			<xs:documentation>Implementation Data Element Note</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IK401_PositionInSegment_2110">
					<xs:annotation>
						<xs:documentation>Code indicating the relative position of the simple data element or composite data structure in error within a segment, count beginning with 1 for the position immediately following the segment ID; additionally indicating the relative position of a repeating structure in error, count beginning with 1 for the position immediately following the preceding element separator; additionally indicating the relative position of a component of a composite data structure in error, count beginning with 1 for the position following the preceding element or repetition separator</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="IK401_01_ElementPositionInSegment">
								<xs:annotation>
									<xs:documentation>This is used to indicate the relative position of a simple data element or the relative position of a composite data structure with the relative position of the component within the composite data structure.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Element Position in Segment" Number="722" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="IK401_02_ComponentDataElementPositionInComposite" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the component data element position within the composite that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Component Data Element Position in Composite" Number="1528" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="IK401_03_RepeatingDataElementPosition" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the specific repetition of a data element that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Repeating Data Element Position" Number="1686" DataType="N0" MaximumLength="4"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="IK402__DataElementReferenceNumber" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Reference number used to locate the data element in the Data Element Dictionary.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Data Element Reference Number" Number="725" DataType="N0" MaximumLength="4"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="6"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK403__ImplementationDataElementSyntaxErrorCode">
					<xs:annotation>
						<xs:documentation>Code indicating the implementation error found after syntax edits of a data element.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Data Element Syntax Error Code" Number="621" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Required Data Element Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Conditional Required Data Element Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Too Many Data Elements</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Data Element Too Short</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Data Element Too Long</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Invalid Character In Data Element</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Invalid Code Value</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Invalid Date</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Invalid Time</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Exclusion Condition Violated</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Too Many Repetitions</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Too Many Components</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I10">
								<xs:annotation>
									<xs:documentation>Implementation "Not Used" Data Element Present</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I11">
								<xs:annotation>
									<xs:documentation>Implementation Too Few Repetitions</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I12">
								<xs:annotation>
									<xs:documentation>Implementation Pattern Match Failure</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I13">
								<xs:annotation>
									<xs:documentation>Implementation Dependent "Not Used" Data Element Present</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Code Value Not Used in Implementation</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I9">
								<xs:annotation>
									<xs:documentation>Implementation Dependent Data Element Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK404__CopyOfBadDataElement" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This is a copy of the data element in error.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Copy of Bad Data Element" Number="724" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="99"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CTX_ElementContext_2110">
		<xs:annotation>
			<xs:documentation>Element Context</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CTX01_ContextIdentification_2110" maxOccurs="10">
					<xs:annotation>
						<xs:documentation>Holds information to identify a context</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX01_01_ContextName">
								<xs:annotation>
									<xs:documentation>Holds the name or `tag' of a context.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Name" Number="9999" DataType="AN"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX01_02" minOccurs="0">
								<xs:annotation>
									<xs:appinfo>
										<x12:STD_Info Name="Context Reference" Number="9998" DataType="AN"/>
										<x12:TR3_Info Used="No"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CTX02__SegmentIDCode">
					<xs:annotation>
						<xs:documentation>Code defining the segment ID of the data segment in error (See Appendix A - Number 77).</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment ID Code" Number="721" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="2"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX03__SegmentPositionInTransactionSet">
					<xs:annotation>
						<xs:documentation>The numerical count position of this data segment from the start of the transaction set: the transaction set header is count position 1.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Segment Position in Transaction Set" Number="719" DataType="N0" MaximumLength="10"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX04__LoopIdentifierCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The loop ID number given on the transaction set diagram is the value for this data element in segments LS and LE.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Loop Identifier Code" Number="447" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CTX05_PositionInSegment_2110" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating the relative position of the simple data element or composite data structure in error within a segment, count beginning with 1 for the position immediately following the segment ID; additionally indicating the relative position of a repeating structure in error, count beginning with 1 for the position immediately following the preceding element separator; additionally indicating the relative position of a component of a composite data structure in error, count beginning with 1 for the position following the preceding element or repetition separator</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX05_01_ElementPositionInSegment">
								<xs:annotation>
									<xs:documentation>This is used to indicate the relative position of a simple data element or the relative position of a composite data structure with the relative position of the component within the composite data structure.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Element Position in Segment" Number="722" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX05_02_ComponentDataElementPositionInComposite" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the component data element position within the composite that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Component Data Element Position in Composite" Number="1528" DataType="N0" MaximumLength="2"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX05_03_RepeatingDataElementPosition" minOccurs="0">
								<xs:annotation>
									<xs:documentation>To identify the specific repetition of a data element that is in error.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Repeating Data Element Position" Number="1686" DataType="N0" MaximumLength="4"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CTX06_ReferenceInSegment_2110" minOccurs="0">
					<xs:annotation>
						<xs:documentation>To hold the reference number of a data element and optionally a component data element within a composite</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CTX06_01_DataElementReferenceNumber">
								<xs:annotation>
									<xs:documentation>Reference number used to locate the data element in the Data Element Dictionary.</xs:documentation>
									<xs:appinfo>
										<x12:STD_Info Name="Data Element Reference Number" Number="725" DataType="N0" MaximumLength="4"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CTX06_02" minOccurs="0">
								<xs:annotation>
									<xs:appinfo>
										<x12:STD_Info Name="Data Element Reference Number" Number="725" DataType="N0" MaximumLength="4"/>
										<x12:TR3_Info Used="No"/>
									</xs:appinfo>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IK5_TransactionSetResponseTrailer_2000">
		<xs:annotation>
			<xs:documentation>Transaction Set Response Trailer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IK501__TransactionSetAcknowledgmentCode">
					<xs:annotation>
						<xs:documentation>Code indicating accept or reject condition based on the syntax editing of the transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Acknowledgment Code" Number="717" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="1"/>
							<xs:enumeration value="A">
								<xs:annotation>
									<xs:documentation>Accepted</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="E">
								<xs:annotation>
									<xs:documentation>Accepted But Errors Were Noted</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="M">
								<xs:annotation>
									<xs:documentation>Rejected, Message Authentication Code (MAC) Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="R">
								<xs:annotation>
									<xs:documentation>Rejected</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="W">
								<xs:annotation>
									<xs:documentation>Rejected, Assurance Failed Validity Tests</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="X">
								<xs:annotation>
									<xs:documentation>Rejected, Content After Decryption Could Not Be Analyzed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK502__ImplementationTransactionSetSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Transaction Set Syntax Error Code" Number="618" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Transaction Set Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Transaction Set Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number in Header and Trailer Do Not Match</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Number of Included Segments Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Identifier</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Control Number</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encrypted) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Transaction Set not in Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Invalid Transaction Set Implementation Convention Reference</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number Not Unique within the Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="27">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I5">
								<xs:annotation>
									<xs:documentation>Implementation One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Convention Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK503__ImplementationTransactionSetSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Transaction Set Syntax Error Code" Number="618" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Transaction Set Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Transaction Set Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number in Header and Trailer Do Not Match</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Number of Included Segments Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Identifier</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Control Number</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encrypted) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Transaction Set not in Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Invalid Transaction Set Implementation Convention Reference</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number Not Unique within the Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="27">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I5">
								<xs:annotation>
									<xs:documentation>Implementation One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Convention Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK504__ImplementationTransactionSetSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Transaction Set Syntax Error Code" Number="618" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Transaction Set Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Transaction Set Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number in Header and Trailer Do Not Match</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Number of Included Segments Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Identifier</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Control Number</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encrypted) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Transaction Set not in Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Invalid Transaction Set Implementation Convention Reference</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number Not Unique within the Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="27">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I5">
								<xs:annotation>
									<xs:documentation>Implementation One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Convention Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK505__ImplementationTransactionSetSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Transaction Set Syntax Error Code" Number="618" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Transaction Set Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Transaction Set Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number in Header and Trailer Do Not Match</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Number of Included Segments Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Identifier</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Control Number</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encrypted) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Transaction Set not in Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Invalid Transaction Set Implementation Convention Reference</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number Not Unique within the Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="27">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I5">
								<xs:annotation>
									<xs:documentation>Implementation One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Convention Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IK506__ImplementationTransactionSetSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating implementation error found based on the syntax editing of a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Implementation Transaction Set Syntax Error Code" Number="618" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Transaction Set Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Transaction Set Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number in Header and Trailer Do Not Match</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Number of Included Segments Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Identifier</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="7">
								<xs:annotation>
									<xs:documentation>Missing or Invalid Transaction Set Control Number</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="8">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="9">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encrypted) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Transaction Set not in Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Invalid Transaction Set Implementation Convention Reference</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>Transaction Set Control Number Not Unique within the Functional Group</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="27">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I5">
								<xs:annotation>
									<xs:documentation>Implementation One or More Segments in Error</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="I6">
								<xs:annotation>
									<xs:documentation>Implementation Convention Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AK9_FunctionalGroupResponseTrailer">
		<xs:annotation>
			<xs:documentation>Functional Group Response Trailer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AK901__FunctionalGroupAcknowledgeCode">
					<xs:annotation>
						<xs:documentation>Code indicating accept or reject condition based on the syntax editing of the functional group.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Acknowledge Code" Number="715" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="1"/>
							<xs:enumeration value="A">
								<xs:annotation>
									<xs:documentation>Accepted</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="E">
								<xs:annotation>
									<xs:documentation>Accepted, But Errors Were Noted.</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="M">
								<xs:annotation>
									<xs:documentation>Rejected, Message Authentication Code (MAC) Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="P">
								<xs:annotation>
									<xs:documentation>Partially Accepted, At Least One Transaction Set Was Rejected</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="R">
								<xs:annotation>
									<xs:documentation>Rejected</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="W">
								<xs:annotation>
									<xs:documentation>Rejected, Assurance Failed Validity Tests</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="X">
								<xs:annotation>
									<xs:documentation>Rejected, Content After Decryption Could Not Be Analyzed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK902__NumberOfTransactionSetsIncluded">
					<xs:annotation>
						<xs:documentation>Total number of transaction sets included in the functional group or interchange (transmission) gorup terminated by the trailer containing this data element.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Number of Transaction Sets Included" Number="97" DataType="N0" MaximumLength="6"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK903__NumberOfReceivedTransactionSets">
					<xs:annotation>
						<xs:documentation>Number of Transaction Sets received.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Number of Received Transaction Sets" Number="123" DataType="N0" MaximumLength="6"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK904__NumberOfAcceptedTransactionSets">
					<xs:annotation>
						<xs:documentation>Number of accepted Transaction Sets in a Functional Group.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Number of Accepted Transaction Sets" Number="2" DataType="N0" MaximumLength="6"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK905__FunctionalGroupSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating error found based on the syntax editing of the functional group header and/or trailer.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Syntax Error Code" Number="716" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Functional Group Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Functional Group Version Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Functional Group Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Group Control Number in the Functional Group Header and Trailer Do Not Agree</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Number of Included Transaction Sets Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Group Control Number Violates Syntax</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encryption) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="14">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Functional Group Control Number not Unique within Interchange</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK906__FunctionalGroupSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating error found based on the syntax editing of the functional group header and/or trailer.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Syntax Error Code" Number="716" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Functional Group Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Functional Group Version Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Functional Group Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Group Control Number in the Functional Group Header and Trailer Do Not Agree</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Number of Included Transaction Sets Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Group Control Number Violates Syntax</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encryption) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="14">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Functional Group Control Number not Unique within Interchange</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK907__FunctionalGroupSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating error found based on the syntax editing of the functional group header and/or trailer.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Syntax Error Code" Number="716" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Functional Group Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Functional Group Version Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Functional Group Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Group Control Number in the Functional Group Header and Trailer Do Not Agree</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Number of Included Transaction Sets Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Group Control Number Violates Syntax</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encryption) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="14">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Functional Group Control Number not Unique within Interchange</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK908__FunctionalGroupSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating error found based on the syntax editing of the functional group header and/or trailer.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Syntax Error Code" Number="716" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Functional Group Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Functional Group Version Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Functional Group Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Group Control Number in the Functional Group Header and Trailer Do Not Agree</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Number of Included Transaction Sets Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Group Control Number Violates Syntax</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encryption) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="14">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Functional Group Control Number not Unique within Interchange</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AK909__FunctionalGroupSyntaxErrorCode" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Code indicating error found based on the syntax editing of the functional group header and/or trailer.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Functional Group Syntax Error Code" Number="716" DataType="ID"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="3"/>
							<xs:enumeration value="1">
								<xs:annotation>
									<xs:documentation>Functional Group Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="2">
								<xs:annotation>
									<xs:documentation>Functional Group Version Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="3">
								<xs:annotation>
									<xs:documentation>Functional Group Trailer Missing</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="4">
								<xs:annotation>
									<xs:documentation>Group Control Number in the Functional Group Header and Trailer Do Not Agree</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="5">
								<xs:annotation>
									<xs:documentation>Number of Included Transaction Sets Does Not Match Actual Count</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="6">
								<xs:annotation>
									<xs:documentation>Group Control Number Violates Syntax</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="10">
								<xs:annotation>
									<xs:documentation>Authentication Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="11">
								<xs:annotation>
									<xs:documentation>Encryption Key Name Unknown</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="12">
								<xs:annotation>
									<xs:documentation>Requested Service (Authentication or Encryption) Not Available</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="13">
								<xs:annotation>
									<xs:documentation>Unknown Security Recipient</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="14">
								<xs:annotation>
									<xs:documentation>Unknown Security Originator</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="15">
								<xs:annotation>
									<xs:documentation>Syntax Error in Decrypted Text</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="16">
								<xs:annotation>
									<xs:documentation>Security Not Supported</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="17">
								<xs:annotation>
									<xs:documentation>Incorrect Message Length (Encryption Only)</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="18">
								<xs:annotation>
									<xs:documentation>Message Authentication Code Failed</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="19">
								<xs:annotation>
									<xs:documentation>Functional Group Control Number not Unique within Interchange</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="23">
								<xs:annotation>
									<xs:documentation>S3E Security End Segment Missing for S3S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="24">
								<xs:annotation>
									<xs:documentation>S3S Security Start Segment Missing for S3E End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="25">
								<xs:annotation>
									<xs:documentation>S4E Security End Segment Missing for S4S Security Start Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
							<xs:enumeration value="26">
								<xs:annotation>
									<xs:documentation>S4S Security Start Segment Missing for S4E Security End Segment</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SE_TransactionSetTrailer">
		<xs:annotation>
			<xs:documentation>Transaction Set Trailer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SE01__NumberOfIncludedSegments">
					<xs:annotation>
						<xs:documentation>Total number of segments included in a transaction set including ST and SE segments.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Number of Included Segments" Number="96" DataType="N0" MaximumLength="10"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SE02__TransactionSetControlNumber">
					<xs:annotation>
						<xs:documentation>The unique identification number within a transaction set.</xs:documentation>
						<xs:appinfo>
							<x12:STD_Info Name="Transaction Set Control Number" Number="329" DataType="AN"/>
						</xs:appinfo>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
