#eiPlatform environment properties (Linux / Docker paths)
DATABASE_DRIVER=org.h2.Driver
DATABASE_PASSWORD=
DATABASE_URL=jdbc\:h2\:/opt/pilotfish/database/medreceivables
DATABASE_USERNAME=sa
FLAT_FILE_ARCHIVE_DIRECTORY=/opt/pilotfish/archive
FLAT_FILE_INPUT_DIRECTORY=/opt/pilotfish/input
FLAT_FILE_STAGE_DIRECTORY=/opt/pilotfish/input/staging
FORM_txtInterfaceType=
FORM_txtPartition=
HL7_TARGET_DIRECTORY=/opt/pilotfish/output
LISTENER_ROUTE_XML_DIR=/usr/local/tomcat/webapps/eip/eip-root/interfaces/Flat File to HL7 and Kickout Reports/routes/1 - Incoming Flat Files by Partition and Client
LISTENER_ROUTE_XML_FILENAME=route.xml
NFL_FLAT_FILE_ARCHIVE_DIRECTORY=data/io/archive/NFL
NFL_FLAT_FILE_INPUT_DIRECTORY=data/io/input/NFL
REPORT_TARGET_DIRECTORY=/opt/pilotfish/output
is_debug=false
max_transactions_per_run_ariana=3000
