#eiPlatform environment properties (EDI 276/277 Claim Status demo)

EDI_INBOUND_DIRECTORY=/opt/pilotfish/input/inbound
EDI_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
FOUND_OUTPUT_DIRECTORY=/opt/pilotfish/output/found
NOT_FOUND_OUTPUT_DIRECTORY=/opt/pilotfish/output/not-found
ERROR_OUTPUT_DIRECTORY=/opt/pilotfish/output/error
RESPONSE_OUTPUT_DIRECTORY=/opt/pilotfish/output/responses
DEBUG_OUTPUT_DIRECTORY=/opt/pilotfish/output/debug
is_debug=true
STAGED_DECISION_DIRECTORY=/opt/pilotfish/output/staged-decisions
