is_debug=true
SFTP_HOST=sftp
SFTP_PORT=22
SFTP_USER=demo
SFTP_PASSWORD=demo
SFTP_POLL_DIR=upload
STAGED_EDI_DIRECTORY=/opt/pilotfish/output/staged
ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
JSON_OUTPUT_DIRECTORY=/opt/pilotfish/output/json
KICKOUT_DIRECTORY=/opt/pilotfish/output/kickout
OCI_NAMESPACE=floci-local
OCI_BUCKET=edi-835-payments
OCI_ENDPOINT=http://floci-oci:4599
OCI_REGION=us-ashburn-1
