#eiPlatform environment properties (FTP Named Download Trigger demo)

CONTROL_INBOUND_DIRECTORY=/opt/pilotfish/input/control
CONTROL_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
DOWNLOAD_OUTPUT_DIRECTORY=/opt/pilotfish/output/downloaded
KICKOUT_DIRECTORY=/opt/pilotfish/output/kickout

SFTP_HOST=sftp
SFTP_PORT=22
SFTP_USER=demo
SFTP_PASSWORD=demo
SFTP_POLL_DIR=upload

is_debug=true
