-- NHL CAT (524) + IRL GAN (523) — CLIENT_SPLITS / CLIENT_CODES / TWEAKING_RULES
-- Applied after deciding SOFTWAREID 524 for CAT (513 remains FPS CNL).

DELETE FROM CLIENT_SPLITS WHERE SOFTWAREID IN (523,524) OR CLIENT IN ('CAT','GAN');
DELETE FROM CLIENT_CODES WHERE SOFTWARE_ID IN (523,524);
DELETE FROM TWEAKING_RULES WHERE CLIENT IN ('CAT','GAN');

INSERT INTO CLIENT_SPLITS (SOFTWAREID, CLIENTNAME, PARTITION, CLIENT, FACILITY, FACILITY_CODE, DEFAULT_PERF_DR, ACCOUNT_NUM_ALPHA, DATE_RANGE, IS_DEFAULT)
VALUES
 (524, 'Catholic Medical', 'NHL', 'CAT', 'CAT', 'HK', 'CP9', 'HK', '20260611', 1),
 (523, 'HCA FL Gainesville Hospital', 'IRL', 'GAN', 'GAN', 'PT', 'CN1', 'PT', '20260505', 1);

INSERT INTO CLIENT_CODES (FACILITY, CODE, COMPARATOR, SOFTWARE_ID) VALUES
 ('CAT', NULL, '!=', 524),
 ('GAN', NULL, '!=', 523);

INSERT INTO TWEAKING_RULES (PARTITION, CLIENT, RULE_NAME) VALUES
 ('NHL', 'CAT', 'Update RadNumTimes If RadCRDBIndicator'),
 ('NHL', 'CAT', 'Sort diagnosis codes using BVWYZ method'),
 ('IRL', 'GAN', 'Update RadNumTimes If RadCRDBIndicator'),
 ('IRL', 'GAN', 'Sort diagnosis codes using BVWYZ method');
