#eiPlatform environment — EDI 835 OCI Bucket

SFTP_HOST=sftp
SFTP_PORT=22
SFTP_USER=demo
SFTP_PASSWORD=demo
SFTP_POLL_DIR=upload

EDI_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive
STAGED_EDI_DIRECTORY=/opt/pilotfish/output/staged
JSON_OUTPUT_DIRECTORY=/opt/pilotfish/output/json
DEBUG_OUTPUT_DIRECTORY=/opt/pilotfish/output/debug
is_debug=true
