USE CRLPlus;
GO
-- Generous nullable schema so SQLXML inserts from Normalized 121 can land on SQL Server.

IF OBJECT_ID('dbo.REQ_INFO','U') IS NOT NULL DROP TABLE dbo.REQ_INFO;
IF OBJECT_ID('dbo.POLICY','U') IS NOT NULL DROP TABLE dbo.POLICY;
IF OBJECT_ID('dbo.PARTY','U') IS NOT NULL DROP TABLE dbo.PARTY;
IF OBJECT_ID('dbo.TRANSACTION_TEXT','U') IS NOT NULL DROP TABLE dbo.TRANSACTION_TEXT;
IF OBJECT_ID('dbo.VALIDATION_ERROR','U') IS NOT NULL DROP TABLE dbo.VALIDATION_ERROR;
IF OBJECT_ID('dbo.ACORD_INFORMATION_EXCHANGE','U') IS NOT NULL DROP TABLE dbo.ACORD_INFORMATION_EXCHANGE;
IF OBJECT_ID('dbo.CANCELLATION_NOT_FOUND','U') IS NOT NULL DROP TABLE dbo.CANCELLATION_NOT_FOUND;
IF OBJECT_ID('dbo.BATCH','U') IS NOT NULL DROP TABLE dbo.BATCH;
IF OBJECT_ID('dbo.CRLTRANSACTION','U') IS NOT NULL DROP TABLE dbo.CRLTRANSACTION;
GO

CREATE TABLE dbo.CRLTRANSACTION (
  TRANSACTION_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSREFGUID NVARCHAR(200) NULL,
  TYPE_TC NVARCHAR(20) NULL,
  TYPE_TXT NVARCHAR(200) NULL,
  EXE_DATE DATETIME NULL,
  MODE_TC NVARCHAR(20) NULL,
  MODE_TXT NVARCHAR(200) NULL,
  TESTINDICATOR NVARCHAR(10) NULL,
  SOURCE_INFO_NAME NVARCHAR(200) NULL,
  SOURCE_INFO_DESCR NVARCHAR(400) NULL,
  PF_SOURCE_CLIENT NVARCHAR(40) NULL,
  TELEDEX_REMOTE_ID NVARCHAR(100) NULL,
  TELEDEX_ORDER_NUM NVARCHAR(100) NULL,
  FLOWNET_ORDER_NUM NVARCHAR(100) NULL,
  CREATED_BY NVARCHAR(100) NULL,
  CREATED_DATE DATETIME NULL DEFAULT GETDATE(),
  LAST_MODIFIED_BY NVARCHAR(100) NULL,
  LAST_MODIFIED_DATE DATETIME NULL,
  LAST_STATUS_DELIVERED_DATE DATETIME NULL,
  ORDER_COMPLETE_DATE DATETIME NULL,
  FINAL_RESULT_DELIVERED_DATE DATETIME NULL,
  FINAL_RESULT_STAGED_DATE DATETIME NULL,
  PF_PROCESSING_KEY NVARCHAR(100) NULL,
  AWAITING_ATTACHMENTS NVARCHAR(1) NULL DEFAULT 'N'
);
CREATE TABLE dbo.POLICY (
  POLICY_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSACTION_ID INT NULL,
  HOLDING_ID NVARCHAR(80) NULL,
  HOLDING_TC NVARCHAR(20) NULL,
  HOLDING_TC_TXT NVARCHAR(200) NULL,
  POLNUMBER NVARCHAR(100) NULL,
  LINEOFBUSINESS_TC NVARCHAR(20) NULL,
  LINEOFBUSINESS_TC_TXT NVARCHAR(200) NULL,
  PRODUCT_TYPE_TC NVARCHAR(20) NULL,
  PRODUCT_TYPE_TC_TXT NVARCHAR(200) NULL,
  PRODUCT_CODE NVARCHAR(80) NULL,
  CARRIER_CODE NVARCHAR(80) NULL,
  PAYMENT_MODE_TC NVARCHAR(20) NULL,
  PAYMENT_MODE_TXT NVARCHAR(200) NULL,
  PAYMENT_METHOD_TC NVARCHAR(20) NULL,
  PAYMENT_METHOD_TXT NVARCHAR(200) NULL,
  INITIAL_PREM_AMT NVARCHAR(40) NULL,
  FACE_AMT NVARCHAR(40) NULL,
  PLAN_NAME NVARCHAR(200) NULL,
  SHORT_NAME NVARCHAR(200) NULL,
  LIFECOVSTATUS_TC NVARCHAR(20) NULL,
  LIFECOVSTATUS_TXT NVARCHAR(200) NULL,
  LIFECOVTYPECODE_TC NVARCHAR(20) NULL,
  LIFECOVTYPECODE_TXT NVARCHAR(200) NULL,
  INDICATORCODE_TC NVARCHAR(20) NULL,
  INDICATORCODE_TXT NVARCHAR(200) NULL,
  CURRENTAMT NVARCHAR(40) NULL,
  PARTICIPANT_PARTY_ID NVARCHAR(80) NULL,
  PARTICIPANT_ID NVARCHAR(80) NULL,
  PARTICIPANT_ROLE_CODE_TC NVARCHAR(20) NULL,
  PARTICIPANT_ROLE_CODE_TXT NVARCHAR(200) NULL,
  TRACKING_ID NVARCHAR(100) NULL,
  APP_JURISDICTION_TC NVARCHAR(20) NULL,
  APP_JURISDICTION_TXT NVARCHAR(200) NULL,
  SIGNED_DATE DATETIME NULL,
  PREF_LANG_TC NVARCHAR(20) NULL,
  PREF_LANG_TXT NVARCHAR(200) NULL,
  IS_PRIMARY_POLICY NVARCHAR(1) NULL,
  PRIORITY NVARCHAR(40) NULL,
  PRIORITY_REASON_ID NVARCHAR(80) NULL
);
CREATE TABLE dbo.PARTY (
  PARTY_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSACTION_ID INT NULL,
  FIRSTNAME NVARCHAR(100) NULL,
  MIDDLENAME NVARCHAR(100) NULL,
  LASTNAME NVARCHAR(100) NULL,
  BIRTHDATE DATE NULL
);
CREATE TABLE dbo.REQ_INFO (
  REQ_INFO_ID INT IDENTITY(1,1) PRIMARY KEY,
  POLICY_ID INT NULL,
  APPLIES_TO_PARTY_ID NVARCHAR(80) NULL,
  REQ_CODE_TC NVARCHAR(20) NULL,
  REQ_CODE_TXT NVARCHAR(200) NULL,
  UNIQUEID NVARCHAR(100) NULL,
  RELEASE_PARTY_ORG_CODE NVARCHAR(80) NULL,
  REQ_ACCT_NUM NVARCHAR(80) NULL,
  REQ_STATUS NVARCHAR(80) NULL,
  REQ_DETAILS NVARCHAR(MAX) NULL,
  REQ_DATE DATETIME NULL,
  REQ_SCHEDULED_DATE_TIME DATETIME NULL,
  REQ_SCHEDULED_END_TIME DATETIME NULL,
  CARRIER_ORDER_NUM NVARCHAR(80) NULL
);
CREATE TABLE dbo.TRANSACTION_TEXT (
  TRANSACTION_TEXT_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSACTION_ID INT NULL,
  ORIGINAL_TXT NVARCHAR(MAX) NULL,
  ORIGINAL_TYPE NVARCHAR(20) NULL,
  NORMALIZED_TXT NVARCHAR(MAX) NULL
);
CREATE TABLE dbo.VALIDATION_ERROR (
  VALIDATION_ERROR_ID INT IDENTITY(1,1) PRIMARY KEY,
  PF_SOURCE_CLIENT NVARCHAR(40) NULL,
  POLNUMBER NVARCHAR(100) NULL,
  ERROR_DATE DATETIME NULL,
  REQ_CODE_TC NVARCHAR(20) NULL,
  REQ_CODE_TXT NVARCHAR(200) NULL,
  REASON_FOR_ERROR NVARCHAR(MAX) NULL,
  TRANSACTION_TEXT_ID INT NULL
);
CREATE TABLE dbo.ACORD_INFORMATION_EXCHANGE (
  AIE_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSACTION_ID INT NULL,
  AIE_MESSAGE_ID NVARCHAR(200) NULL,
  AIE_FROM NVARCHAR(200) NULL,
  AIE_FROM_SERVICE NVARCHAR(200) NULL,
  AIE_TO NVARCHAR(200) NULL,
  AIE_TO_SERVICE NVARCHAR(200) NULL,
  AIE_REPLY_TO NVARCHAR(200) NULL,
  AIE_REPLY_TO_SERVICE NVARCHAR(200) NULL
);
CREATE TABLE dbo.CANCELLATION_NOT_FOUND (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  PF_SOURCE_CLIENT NVARCHAR(40) NULL,
  CARRIER_CODE NVARCHAR(80) NULL,
  POLNUMBER NVARCHAR(100) NULL,
  TRACKING_ID NVARCHAR(100) NULL,
  REQ_INFO_UNIQUE_ID NVARCHAR(100) NULL,
  CARRIER_ORDER_NUM NVARCHAR(80) NULL,
  TRANSACTION_DATE DATETIME NULL,
  RECEIVED_DATE DATETIME NULL
);
CREATE TABLE dbo.ATTACHMENT (
  ATTACHMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
  TRANSACTION_ID INT NULL,
  STATUS_ID NVARCHAR(40) NULL,
  BASICTYPE_TC NVARCHAR(20) NULL,
  BASICTYPE_TXT NVARCHAR(200) NULL,
  DESCR NVARCHAR(MAX) NULL,
  TYPE_TC NVARCHAR(20) NULL,
  TYPE_TXT NVARCHAR(200) NULL,
  MIMETYPE NVARCHAR(100) NULL,
  ENCTYPESTR NVARCHAR(80) NULL,
  ENCTYPE_TC NVARCHAR(20) NULL,
  LOCATION_TC NVARCHAR(20) NULL,
  CRL_DOCUMENT_ID NVARCHAR(80) NULL,
  CRL_FOLDER_ID NVARCHAR(80) NULL,
  CRL_DRAWER_NAME NVARCHAR(80) NULL,
  CRL_PAGE_COUNT NVARCHAR(20) NULL
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'pilotfish')
  CREATE LOGIN pilotfish WITH PASSWORD = 'PilotFish_Demo1!', CHECK_POLICY = OFF;
USE CRLPlus;
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'pilotfish')
  CREATE USER pilotfish FOR LOGIN pilotfish WITH DEFAULT_SCHEMA = dbo;
ALTER ROLE db_owner ADD MEMBER pilotfish;
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'pilotfish')
  EXEC('CREATE SCHEMA pilotfish AUTHORIZATION pilotfish');
-- SQLXML RestrictMetaDataToSchema uses db.username
IF OBJECT_ID('pilotfish.CRLTRANSACTION','U') IS NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.CRLTRANSACTION');
IF OBJECT_ID('pilotfish.POLICY','U') IS NULL AND OBJECT_ID('dbo.POLICY','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.POLICY');
IF OBJECT_ID('pilotfish.PARTY','U') IS NULL AND OBJECT_ID('dbo.PARTY','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.PARTY');
IF OBJECT_ID('pilotfish.REQ_INFO','U') IS NULL AND OBJECT_ID('dbo.REQ_INFO','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.REQ_INFO');
IF OBJECT_ID('pilotfish.TRANSACTION_TEXT','U') IS NULL AND OBJECT_ID('dbo.TRANSACTION_TEXT','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.TRANSACTION_TEXT');
IF OBJECT_ID('pilotfish.VALIDATION_ERROR','U') IS NULL AND OBJECT_ID('dbo.VALIDATION_ERROR','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.VALIDATION_ERROR');
IF OBJECT_ID('pilotfish.ACORD_INFORMATION_EXCHANGE','U') IS NULL AND OBJECT_ID('dbo.ACORD_INFORMATION_EXCHANGE','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.ACORD_INFORMATION_EXCHANGE');
IF OBJECT_ID('pilotfish.CANCELLATION_NOT_FOUND','U') IS NULL AND OBJECT_ID('dbo.CANCELLATION_NOT_FOUND','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.CANCELLATION_NOT_FOUND');
IF OBJECT_ID('pilotfish.BATCH','U') IS NULL AND OBJECT_ID('dbo.BATCH','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.BATCH');
IF OBJECT_ID('pilotfish.ATTACHMENT','U') IS NULL AND OBJECT_ID('dbo.ATTACHMENT','U') IS NOT NULL
  EXEC('ALTER SCHEMA pilotfish TRANSFER dbo.ATTACHMENT');
ALTER TABLE pilotfish.PARTY ADD
  ACORD_PARTY_ID NVARCHAR(80) NULL,
  PARTY_TC NVARCHAR(20) NULL,
  PARTY_TC_TXT NVARCHAR(200) NULL,
  GOVTID NVARCHAR(80) NULL,
  OCCUPATION NVARCHAR(200) NULL,
  GENDER_TC NVARCHAR(20) NULL,
  GENDER_TXT NVARCHAR(80) NULL,
  CITIZENSHIP_TC NVARCHAR(20) NULL,
  CITIZENSHIP_TXT NVARCHAR(80) NULL,
  BIRTHCOUNTRY_TC NVARCHAR(20) NULL,
  BIRTHCOUNTRY_TXT NVARCHAR(80) NULL,
  BIRTHJURISDICTION_TC NVARCHAR(20) NULL,
  PREFIX NVARCHAR(40) NULL,
  FULLNAME NVARCHAR(255) NULL,
  RESIDENCE_ST_TC NVARCHAR(20) NULL,
  RESIDENCE_ST_TXT NVARCHAR(80) NULL,
  RESIDENCE_CTRY_TC NVARCHAR(20) NULL,
  RESIDENCE_CTRY_TXT NVARCHAR(80) NULL,
  BESTTIMETOCALLFROM NVARCHAR(20) NULL,
  BESTTIMETOCALLTO NVARCHAR(20) NULL,
  CLIENT_KEY NVARCHAR(80) NULL;
GO
-- Status poll / 1122 map expect Oracle STATUS_EVENT_* names.
IF COL_LENGTH('pilotfish.STATUS','STATUS_EVENT_DATE') IS NULL
  ALTER TABLE pilotfish.STATUS ADD STATUS_EVENT_DATE DATETIME NULL;
IF COL_LENGTH('pilotfish.STATUS','STATUS_EVENT_TYPE_CODE') IS NULL
  ALTER TABLE pilotfish.STATUS ADD STATUS_EVENT_TYPE_CODE NVARCHAR(40) NULL;
IF COL_LENGTH('pilotfish.STATUS','STATUS_EVENT_DETAIL') IS NULL
  ALTER TABLE pilotfish.STATUS ADD STATUS_EVENT_DETAIL NVARCHAR(400) NULL;
GO
