#eiPlatform environment properties (EDI 834 CSV Excel Conversion)

CSV_INBOUND_DIRECTORY=/opt/pilotfish/input/inbound
CSV_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive/csv
EDI_INBOUND_DIRECTORY=/opt/pilotfish/input/edi
EDI_ARCHIVE_DIRECTORY=/opt/pilotfish/output/archive/edi
EDI_834_OUTPUT_DIRECTORY=/opt/pilotfish/output/834
CSV_OUTPUT_DIRECTORY=/opt/pilotfish/output/csv
KICKOUT_DIRECTORY=/opt/pilotfish/output/kickout
is_debug=true
