# American Income Life (AIL) environment properties
AILIncomingAuthFile=auth-test.txt
AILOutgoingWsURL=http://localhost:8095/ail/status
AILOutgoingWsUserName=ail-out
AILOutgoingWsPassword=AilOutSandbox1
